### ISSUE TITLE
(NOT ISSUE) Why katana cannot be run on Windows?

### ISSUE THREAD

**Issue by diamond-gold** [Hydreon/Katana#36]
Can i know what is preventing katana from running on WIndows Machines? I might want to try and fix it.

**Comment by legoboy0215** [comment]
Performance issue?

**Comment by RandomAltThingy** [comment]
I have a theory why they cut it out:

Katana is for large minigame servers, and they are not normally hosted on a Windows PC. Katana is directed towards Linux, as it has better performance than Windows (By a long shot).

Because the majority of people host servers on Linux (You may not even realise - that leet servers you just bought? That runs on a Linux VPS), they probably decided to cut out Windows support to increase performance.

**Comment by KnownUnown** [comment]
This is not a questions forum, don't ask questions here.
Katana actually runs on Windows, but due to how hard it is to support many different platforms, we have decided not to help anyone with Windows.
